version: '3.8'

services:
  database:
    hostname: database
    image: docker.io/postgres:latest
    environment:
      POSTGRES_PASSWORD: salasana
      PGUSER: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - db_net
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-run:/var/run/postgresql
    ports:
      - 127.0.0.1:5432:5432
